### ISSUE TITLE
non-ascii journal titles

### ISSUE THREAD

**Issue by kaplun** [inspirehep/refextract#25]
https://sentry.cern.ch/inspire-sentry/inspire-labs/group/820653/

**Comment by michamos** [comment]
this is not a `refextract` bug, the default format string was changed to unicode in #16, but `inspire-next` uses a different one that should be fixed as part of inspirehep/inspire-next#2133.

**Comment by michamos** [comment]
@chris-asl the problem is here https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/refextract/tasks.py#L90

**Comment by kaplun** [comment]
Are you sure? The exception is triggered deep down in refextract code base.

**Comment by michamos** [comment]
Yes, the format string gets passed to refextract and consumed deep inside (one of refextract great design decisions).

**Comment by kaplun** [comment]
:scream:
