### ISSUE TITLE
TypeError: coercing to Unicode

### ISSUE THREAD

**Issue by darjusp** [inspirehep/refextract#41]
Hi guys, 
i installed refextract and bumped into this error. it happens no matter what file i am trying to open, whether from source or from url. For instance:
`from refextract import extract_references_from_url
reference = extract_references_from_url("http://arxiv.org/pdf/1503.07589v1.pdf")`
Any ideas how to solve it?

**The error:**
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-399baa469642> in <module>()
      1 from refextract import extract_references_from_url
----> 2 reference = extract_references_from_url("http://arxiv.org/pdf/1503.07589v1.pdf")

/Users/pacausd1/anaconda/envs/python2/lib/python2.7/site-packages/refextract/references/api.pyc in extract_references_from_url(url, headers, chunk_size, **kwargs)
     92             for chunk in req.iter_content(chunk_size):
     93                 f.write(chunk)
---> 94         references = extract_references_from_file(filepath, **kwargs)
     95     except requests.exceptions.HTTPError as e:
     96         raise FullTextNotAvailableError("URL not found: '{0}'".format(url)), None, sys.exc_info()[2]

/Users/pacausd1/anaconda/envs/python2/lib/python2.7/site-packages/refextract/references/api.pyc in extract_references_from_file(path, recid, reference_format, linker_callback, override_kbs_files)
    132         raise FullTextNotAvailableError("File not found: '{0}'".format(path))
    133 
--> 134     docbody = get_plaintext_document_body(path)
    135     reflines, dummy, dummy = extract_references_from_fulltext(docbody)
    136     if not reflines:

/Users/pacausd1/anaconda/envs/python2/lib/python2.7/site-packages/refextract/references/engine.pyc in get_plaintext_document_body(fpath, keep_layout)
   1400 
   1401     elif mime_type == "application/pdf":
-> 1402         textbody = convert_PDF_to_plaintext(fpath, keep_layout)
   1403 
   1404     else:

/Users/pacausd1/anaconda/envs/python2/lib/python2.7/site-packages/refextract/documents/pdf.pyc in convert_PDF_to_plaintext(fpath, keep_layout)
    487     into plaintext; each string is a line in the document.)
    488     """
--> 489     if not os.path.isfile(CFG_PATH_PDFTOTEXT):
    490         raise FileNotFoundError('Missing pdftotext executable')
    491 

/Users/pacausd1/anaconda/envs/python2/lib/python2.7/genericpath.pyc in isfile(path)
     35     """Test whether a path is a regular file"""
     36     try:
---> 37         st = os.stat(path)
     38     except os.error:
     39         return False

TypeError: coercing to Unicode: need string or buffer, NoneType found`

**Comment by jacquerie** [comment]
From the stacktrace it looks like `CFG_PATH_PDFTOTEXT` is `None` in your installation, which means that https://github.com/inspirehep/refextract/blob/4e14d6c3ea0aad9b8d4c1a5bec9a45da9aa28f54/refextract/references/config.py#L41 did return `None`. Do you have `pdftotext` installed on your system?

**Comment by darjusp** [comment]
That's a good point. Actually i didn't have, and i tried to install and now ran into:
`error: command 'gcc' failed with exit status 1` which i believe has nothing to do with refextract. Actually after all day of trying to install the package i couldn't :) And i just would like to try it, to see what outcome it produces on my data.
Can some nice person try to upload to refextact these files and post to me the result?
https://mega.nz/#!lCAxQS4J!WQiiSFvrNiBMF1IqoNamlDSWakY7211pIN0xw48Ob9E
I just would like to check the outcome of the tool.

**Comment by michamos** [comment]
@darjusp I had a quick look at your PDFs, and would not expect `refextract` to work well for your purposes, as it needs to be taught what is a journal title. It ships with a list of journals relevant for High Energy Physics in https://github.com/inspirehep/refextract/blob/master/refextract/references/kbs/journal-titles.kb, but you would need to provide your own. I would suggest trying [Grobid](https://github.com/kermitt2/grobid) instead, which should be more flexible.

**Comment by darjusp** [comment]
Michamos thanks a lot, this save lot of my time.
And definitely will try Grobid

**Comment by michamos** [comment]
@darjusp :+1: I will close this issue then.
