### ISSUE TITLE
Error in importing

### ISSUE THREAD

**Issue by anupamag21** [inspirehep/refextract#42]
`(tensorflow_keras) C:\Users\anupamag\Desktop\PYTHON Examples>python paper_stats.
py
Traceback (most recent call last):
  File "paper_stats.py", line 3, in <module>
    import refextract
  File "C:\Users\anupamag\AppData\Local\Continuum\Anaconda3\envs\tensorflow_kera
s\lib\site-packages\refextract\__init__.py", line 28, in <module>
    from .references.api import (
  File "C:\Users\anupamag\AppData\Local\Continuum\Anaconda3\envs\tensorflow_kera
s\lib\site-packages\refextract\references\api.py", line 96
    raise FullTextNotAvailableError("URL not found: '{0}'".format(url)), None, s
ys.exc_info()[2]
                                                                       ^
SyntaxError: invalid syntax
`

This error turns up simply while importing the module:

`
import sys
import re

from refextract import extract_journal_reference
from refextract import extract_references_from_file
from refextract import extract_references_from_url

reference = extract_references_from_url("https://arxiv.org/pdf/1704.06040.pdf")
print(reference)
`

I'm using Python 3.5.3.  Is this a known issue?

**Comment by michamos** [comment]
Thanks for reporting this issue. Currently, we are only testing on Python 2.7. I fixed the bug you reported and added Python 3 to the test matrix in #43 but more work is required to make it Python 3 compatible.

Another problem is that you are using windows, and that refextract uses `pdftotext` (which is part of `poppler`). I don't know how complex it is to install it on windows.

Besides, `refextract` is tuned for High Energy Physics literature, so not sure it would work well for Machine Learning literature (see discussion in #41 for details and alternatives).

**Comment by anupamag21** [comment]
Ah, thank you for the response.  I did not know earlier that this is untested on Python 3.  No worries.

Also, thanks for the suggestion.  That saves a lot of my time.  Cheers!
